### ISSUE TITLE
Lots of Received unknown response errors

### ISSUE THREAD

**Issue by Jev1337** [Melonai/rust-nitro-sniper#9] opened 2020-08-17 10:21 UTC
![F2B9B254-F23A-41A5-B91A-3CE49E9746AA](https://user-images.githubusercontent.com/19759761/90385891-a8741300-e07b-11ea-9e6b-e5407bcfffb6.jpeg)
I run two snipers for testing purposes , i don’t mind the risk of getting banned but i receive unknown response with rns and the other sniper receives already redeemed? I don’t what could possibly be wrong

**Comment by fokshadev** [comment] 2020-08-17 11:46
We couldn't reproduce the error you shown, we're adding some more verbosity to the unknown code message you shown to include the status code, to help us reproduce the error.

**Comment by melnary** [comment] 2020-08-17 13:46
In the latest release 2.2.3 I've added some more verbosity on what exactly happened if an unknown response was received. Could you please try running that again?

**Comment by Jev1337** [comment] 2020-08-17 14:53
> e 2.2.3 I've added some more verbosity on what exactly happened if an unkn

Sure!

It's now running, I'll send a screenshot as soon as I can!

**Comment by Jev1337** [comment] 2020-08-18 06:46
![image](https://user-images.githubusercontent.com/19759761/90479630-dfebc980-e126-11ea-8a6b-4bb6f0b9e4d7.png)

**Comment by Jev1337** [comment] 2020-08-18 10:37
It disconnected from my acc too for some reasons and connected back

**Comment by fokshadev** [comment] 2020-08-18 10:58
> It disconnected from my acc too for some reasons and connected back

It only happens when there is a minor outage, or you lost internet connection for a bit.

**Comment by Jev1337** [comment] 2020-08-18 11:01
> happens when there is a minor outage, or

Probably the minor outage cus I'm using Microsoft Azure's RDPs xD

I host a gaming server with it didn't stop workin, also weird how only 1 of 3 disconnected :v 

Any updates about this?
![image](https://user-images.githubusercontent.com/19759761/90505594-c8263c80-e14a-11ea-9a57-b19b69d16d8d.png)

**Comment by melnary** [comment] 2020-08-18 11:21
> Any updates about this?

We just figured it out. Usually, Discord bots (and therefore selfbots, too) receive 403 errors if they try to access a resource they do not have the permissions to see. In our case a request to redeem a Nitro code always includes a channel ID where this code was found at. If the account that is trying to redeem the Nitro is not in this channel, you get a 403. It may be that the channel ID is not even required in the request, but we need to test more to find out.

**Comment by Jev1337** [comment] 2020-08-18 11:31
Well, If the channel ID is not required and It still snipes, Then remove it ^^

I'll keep testing

**Comment by melnary** [comment] 2020-08-18 15:36
> Then remove it

It could be important, because the Discord client itself actually sends these two properties as the request body as it tries to redeem.

<img width="532" alt="Screenshot 2020-08-18 at 17 33 54" src="https://user-images.githubusercontent.com/10659529/90533600-0aff0900-e179-11ea-8878-d3dce3096edc.png">

This easily could just be ignored by the back-end, but it might also be the difference between sniping the code and getting blocked by Discord. Anyway, I'll remove this property from the request entirely, but I can't guarantee it'll manage to successfully snipe anything this way. Nevertheless, this has to be tested!

**Comment by Jev1337** [comment] 2020-08-18 16:55
> > Then remove it
> 
> It could be important, because the Discord client itself actually sends these two properties as the request body as it tries to redeem.
> 
> <img alt="Screenshot 2020-08-18 at 17 33 54" width="532" src="https://user-images.githubusercontent.com/10659529/90533600-0aff0900-e179-11ea-8878-d3dce3096edc.png">
> 
> This easily could just be ignored by the back-end, but it might also be the difference between sniping the code and getting blocked by Discord. Anyway, I'll remove this property from the request entirely, but I can't guarantee it'll manage to successfully snipe anything this way. Nevertheless, this has to be tested!

Welp, Btw by any chance, Can we talk on discord? I don't like Git too much for communication xD

**Comment by fokshadev** [comment] 2020-08-18 21:29
Sure, what's your DiscorD?

**Comment by Jev1337** [comment] 2020-08-18 23:36
![image](https://user-images.githubusercontent.com/19759761/90575764-0a379880-e1b4-11ea-98fd-51379c02fa8c.png)


> Sure, what's your DiscorD?

PolizeiRocket#0017

**Comment by melnary** [comment] 2020-08-19 20:17
Fixed in RNS 2.3.0!

**Closed as completed by melnary** 2020-08-19 20:17 UTC
